<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P53AVDF" failures="3" tests="12" name="Parallel Tests chrome" time="22.493" errors="0" timestamp="2024-08-03T13:42:00 EDT">
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.024"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.002"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="demo0" time="0.209">
    <skipped/>
  </testcase> <!-- demo0 -->
  <testcase classname="MyTests.FirstSeleniumScript" name="dataProviderTest" time="0.001"/>
  <testcase classname="MyTests.FirstSeleniumScript" name="aha" time="0.35">
    <skipped/>
  </testcase> <!-- aha -->
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="0.276">
    <skipped/>
  </testcase> <!-- demo1 -->
  <testcase classname="MyTests.FirstSeleniumScript" name="demo0" time="0.085">
    <skipped/>
  </testcase> <!-- demo0 -->
  <testcase classname="MyTests.FirstSeleniumScript" name="aha" time="0.185">
    <skipped/>
  </testcase> <!-- aha -->
  <testcase classname="MyTests.FirstSeleniumScript" name="demo0" time="0.025">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Selenium] but found [Seleniu]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Selenium] but found [Seleniu]
at MyTests.FirstSeleniumScript.demo0(FirstSeleniumScript.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- demo0 -->
  <testcase classname="MyTests.FirstSeleniumScript" name="aha" time="0.553">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: element not found
  (Session info: chrome=127.0.6533.89)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.19.1&amp;apos;, revision: &amp;apos;abe0ee07dc&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.11&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ef779a0d5e36b82a3b78f6ecf57610e1, getElementAttribute {id=f.5184EC56681EB926CD47A332EC6E964B.d.7624A5A13ACEB8943D87D33B3A662816.e.121, name=innerText}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.89, chrome: {chromedriverVersion: 127.0.6533.88 (a2d0cb026721..., userDataDir: C:\Users\siddu\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:12817}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:12817/devtoo..., se:cdpVersion: 127.0.6533.89, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (ef779a0d5e36b82a3b78f6ecf57610e1)] -&amp;gt; xpath: //div[@id=&amp;apos;main_navbar&amp;apos;]//li//a]
Session ID: ef779a0d5e36b82a3b78f6ecf57610e1">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: element not found
  (Session info: chrome=127.0.6533.89)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ef779a0d5e36b82a3b78f6ecf57610e1, getElementAttribute {id=f.5184EC56681EB926CD47A332EC6E964B.d.7624A5A13ACEB8943D87D33B3A662816.e.121, name=innerText}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.89, chrome: {chromedriverVersion: 127.0.6533.88 (a2d0cb026721..., userDataDir: C:\Users\siddu\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:12817}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:12817/devtoo..., se:cdpVersion: 127.0.6533.89, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (ef779a0d5e36b82a3b78f6ecf57610e1)] -> xpath: //div[@id='main_navbar']//li//a]
Session ID: ef779a0d5e36b82a3b78f6ecf57610e1
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:149)
at MyTests.FirstSeleniumScript.aha(FirstSeleniumScript.java:82)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- aha -->
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="11.195">
    <skipped/>
  </testcase> <!-- demo1 -->
  <testcase classname="MyTests.FirstSeleniumScript" name="demo1" time="5.412">
    <failure type="java.lang.AssertionError" message="expected [8] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [2]
at MyTests.FirstSeleniumScript.demo1(FirstSeleniumScript.java:73)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
</testsuite> <!-- Parallel Tests chrome -->
